import re
from pathlib import Path
from typing import Annotated, ClassVar

from pydantic import BeforeValidator
from pydantic.fields import Field
from pydantic.types import FilePath
# For Python backward compatibility (3.11 and below)
from typing_extensions import Self

from touchstone_testreport.models._base import BaseTestEntityModel, TestCaseResult
from touchstone_testreport.models._test_set import TestSetModel


class TestSuiteModel(BaseTestEntityModel):
    """
    Represents Test Suite execution data
    """

    # Constants
    VALID_SOURCE_FILE_PATTERNS: ClassVar[list[str]] = [
        # r'.*',
        # r'^(?!.*set_summary\.csv$)_summary\.csv$',
        r'^(?!.*_set_summary\.csv$).*_summary\.csv$'
    ]

    name: Annotated[
        str,
        BeforeValidator(lambda val: str(val).replace('__summary.csv', '').replace('_summary.csv', ''))
    ] = Field(
        default='Unknown',
        description='Unique test suite name',
        validation_alias='TestSuiteName',
    )

    source_file: Annotated[
        FilePath,
        BeforeValidator(
            lambda val: Path(
                val if any(
                    [bool(re.compile(pattern_str).match(str(val)))
                     for pattern_str in TestSuiteModel.VALID_SOURCE_FILE_PATTERNS]
                )
                else Path.cwd()
            ).resolve().absolute()
        )
    ] = Field(
        description='Path to the test suite execution summary file'
    )

    test_sets: dict[str, TestSetModel] = Field(
        default_factory=dict,
        description='List of associated test sets',
    )

    test_results: dict[TestCaseResult, int] = Field(
        default_factory=lambda: {result: 0 for result in TestCaseResult},
        description='Dictionary of test results with their counts for all test sets',
    )

    @property
    def total_sets_count(self) -> int:
        return len(self.test_sets)

    @property
    def total_cases_count(self) -> int:
        return sum([test_set.total_cases_count for test_set in self.test_sets.values()])

    @classmethod
    def from_csv(cls, in_file: Path) -> Self:
        """
        Generates the TestSet instance from a CSV file

        :param in_file: Path to the CSV file containing test case execution data,
                        generated by Touchstone on each test set run e.g. '<your-path>/_summary.csv'
        :raises: ValidationError
        """
        suite: Path = Path(in_file)
        test_suite: Self = cls(TestSuiteName=suite.name, source_file=suite)
        test_suite.test_sets.update(TestSetModel.from_csv(suite))

        if len(test_suite.test_sets) == 0:
            raise ValueError(f'{test_suite.name} has no test sets, skipping...')
        for test_set in test_suite.test_sets.values():
            for result in test_suite.test_results:
                test_suite.test_results[result] += test_set.test_results[result]

        return test_suite
