from csv import DictReader
from pathlib import Path
from typing import Annotated, Self

from pydantic import ValidationError
from pydantic.fields import Field
from pydantic.types import StringConstraints

from touchstone_testreport.models._base import BaseTestEntityModel, TestCaseResult
from touchstone_testreport.models._test_case import TestCaseModel


class TestSetModel(BaseTestEntityModel):
    """
    Represents Test Set execution data
    It's a weak entity and dependent on TestSuite for unique identity
    """
    name: Annotated[str, StringConstraints(to_upper=True)] = Field(
        default='Unknown',
        description='Unique test set name',
        validation_alias='TestSetName',
    )

    test_cases: list[TestCaseModel] = Field(
        default_factory=list,
        description='List of associated test cases',
    )

    test_results: dict[TestCaseResult, int] = Field(
        default_factory=lambda: {result: 0 for result in TestCaseResult},
        description='Dictionary of test results with their counts for all test cases',
    )

    @property
    def total_cases_count(self) -> int:
        return len(self.test_cases)

    @classmethod
    def from_csv(cls, in_file: Path) -> dict[str, Self]:
        """
        Generates the TestSet instance from a CSV file

        :param in_file: Path to the CSV file containing test case execution data,
                        generated by Touchstone on each test set run e.g. '<your-path>/_summary.csv'
        """
        test_sets: dict[str, Self] = dict()
        with in_file.open(mode='r', encoding='utf-8') as file:
            test_set: Self

            reader: DictReader[str] = DictReader(file)
            for row in reader:
                try:
                    test_set = cls(**row)
                except (ValidationError, TypeError) as error:
                    # TODO: Add logging
                    continue
                if test_set.name not in test_sets:
                    test_sets[test_set.name] = test_set

                case: TestCaseModel = TestCaseModel(**row)
                test_set: TestSetModel = test_sets[test_set.name]
                test_set.test_results[case.result] += 1
                test_set.test_cases.append(case)

        return test_sets
