from csv import DictReader
from pathlib import Path
from typing import Annotated

from pydantic import BeforeValidator, ValidationError
from pydantic.fields import Field
from pydantic.types import PositiveFloat
# For Python backward compatibility (3.11 and below)
from typing_extensions import Self

from touchstone_testreport.models._base import BaseTestEntityModel, TestCaseResult


class TestCaseModel(BaseTestEntityModel):
    """
    Represents Test Case execution data
    It's a weak entity and dependent on TestSet for unique identity
    """
    id: int = Field(
        default=-1,
        description='Unique Test case identifier',
        alias='ID',
    )

    internal_id: str = Field(
        default='Unknown',
        description='Identifier name that Touchstone uses for test case definition',
        alias='TestCaseName',
    )

    description: str = Field(
        default='Unknown',
        description='Test case description',
        alias='Description',
    )

    is_ignored: Annotated[bool, BeforeValidator(lambda val: str(val).lower() == 'ignorable')] = Field(
        default=False,
        description='Whether the test case was ignored or not',
        alias='IsIgnorable',
    )

    result: Annotated[TestCaseResult, BeforeValidator(lambda val: TestCaseResult.get(val))] = Field(
        default='Unknown',
        description='Test case execution result',
        alias='Result',
    )

    run_id: str = Field(
        default='Unknown',
        description='Unique test case execution run identifier',
        alias='TestRunID'
    )

    elapsed_time: Annotated[
        # Promoted type from int -> float for future considerations
        float,
        PositiveFloat
    ] = Field(
        default=0.00,
        description='Elapsed time for test case execution in seconds',
        alias='Elapse',
        ge=0
    )

    @classmethod
    def from_csv(cls, in_file: Path) -> list[Self]:
        """
        Generates the TestCase instance from a CSV file

        :param in_file: Path to the CSV file containing test case execution data,
                        generated by Touchstone on each test set run e.g. '<your-path>/_summary.csv'
        """
        test_cases: list[Self] = list()
        with in_file.open(mode='r', encoding='utf-8') as file:
            reader: DictReader[str] = DictReader(file)
            for row in reader:
                try:
                    test_cases.append(cls(**row))
                except (ValidationError, TypeError) as error:
                    # TODO: Add logging
                    continue

        return test_cases
